version: '3.3'
services:
  dbserver:
    image: mysql:8.0
    labels:
      ho.ctf.cyrhades: dbserver
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=agence_immo

    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: ho-dbserver
  webserver:
    build: server_1/
    labels:
      ho.ctf.cyrhades: webserver
    ports:
      - "80:80"
    container_name: ho-webserver
    depends_on:
      - dbserver
volumes:
  db: