services:
  dbserver:
    image: mysql:8.0
    labels:
      ho.ctf.cyrhades: "1"
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=agence_immo
    volumes:
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  webserver:
    build: ./.docker/server_http
    labels:
      ho.ctf.cyrhades: "1"
    ports:
      - ${PORT}:80
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    depends_on:
      - dbserver
volumes:
  db:
    labels:
      ho.ctf.cyrhades: "1"